version: '3'

services:
  react-app:
    stdin_open: true
    container_name: react-spa
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_VERSION=14
    networks:
      - react-network

networks:
  react-network:
